# Generated by Django 4.2.3 on 2023-12-18 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='message_sender',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='message_target',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
