# Generated by Django 4.2.4 on 2023-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_messagemodel_message_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PwChangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('new_password', models.CharField(max_length=255)),
            ],
        ),
    ]
