# Generated by Django 4.2.4 on 2023-12-21 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_personalinfomodel_alter_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfomodel',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
