# Generated by Django 4.2.4 on 2023-12-21 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_personalinfomodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
