# Generated by Django 4.2.3 on 2023-12-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_textlimit_messagelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelimit',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textlimit',
            name='text_count',
            field=models.IntegerField(default=0),
        ),
    ]
